-- Create table products
CREATE TABLE PRODUCT (
    PRODUCT_ID INT IDENTITY(1,1),
    PRODUCT VARCHAR(100),
    PRODUCT_CATEGORY VARCHAR(50),
    PRODUCT_TYPE VARCHAR(50),
    SALES NUMERIC(20,2)
);

-- Insert sample data
INSERT INTO PRODUCT VALUES ('Prod1', 'Cat1', 'Type1', 1000);
INSERT INTO PRODUCT VALUES ('Prod2', 'Cat1', 'Type1', 1500);
INSERT INTO PRODUCT VALUES ('Prod3', 'Cat2', 'Type2', 2000);
INSERT INTO PRODUCT VALUES ('Prod4', 'Cat2', 'Type2', 1200);
INSERT INTO PRODUCT VALUES ('Prod5', 'Cat3', 'Type1', 800);

-- Summary hierarchy
SELECT
    PRODUCT_TYPE,
    PRODUCT_CATEGORY,
	PRODUCT,
    SUM(SALES) AS TOTAL_SALES
FROM
    PRODUCT
GROUP BY 
ROLLUP
    (PRODUCT_TYPE, PRODUCT_CATEGORY, PRODUCT);


-- Hierarchy for each combination
SELECT
    PRODUCT_TYPE,
    PRODUCT_CATEGORY,
	PRODUCT,
    SUM(SALES) AS TOTAL_SALES
FROM
    PRODUCT
GROUP BY 
CUBE
    (PRODUCT_TYPE, PRODUCT_CATEGORY, PRODUCT);
